export const projectsData = [
    {
      id: 1,
      title: "First React Portfolio Website",
      description: "Project 1 description",
      image: "/images/projects/firstporto.png",
      // tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://avanfabian.vercel.app/",
    },
    {
      id: 2,
      title: "Cry Cast",
      description: "Project 2 description",
      image: "/images/projects/crycast.png",
      // tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://crycast.000webhostapp.com/",
    },
    {
      id: 3,
      title: "PromptWorld",
      description: "Project 3 description",
      image: "/images/projects/promptworld.png",
      // tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://promptworld-danis.vercel.app/",
    },
    {
      id: 4,
      title: "SchEducation",
      description: "Project 4 description",
      image: "/images/projects/scheducation2.png",
      // tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "https://sch-education.vercel.app/",
    },
    {
      id: 5,
      title: "Personal Blog",
      description: "Authentication and CRUD operations",
      image: "/images/projects/5.png",
      // tag: ["All", "Web"],
      gitUrl: "/",
      previewUrl: "/",
    },
  ];